### ISSUE TITLE
Resolve ActiveRecord model and pull column types into doc

### ISSUE THREAD

**Issue by mxmCherry** [bsm/grape-apidoc#3]
If ActiveRecord is used 

*Maybe* traverse `entity_class.ancestors` till last `ancestor.is_a?(Grape::Entity)` + has max count of `documentation.keys.count`.

Ideally, for both entity (unless type is specified) and accepted route params.

**Comment by dim** [comment]
No, let's not do that, docs need to be manually specified on the entity
